In [2]:
import re
import os
import glob
import pandas as pd

In [6]:
TRANSCRIPT_PATH = "dca_d1_1.txt"

In [7]:
with open(TRANSCRIPT_PATH, "r", encoding="utf-8", errors="ignore") as f:
    raw_text = f.read()

print(raw_text[:3000])

((TAPE-HEADER "DCA TAPE 2; WASHINGTON NATIONAL ATCT; DEPARTURE RADAR CONTROLLER (DR1); 118.95 MHZ; MAY 26, 1992, 1524 EDT; TRANSCRIBER JLO"))

((COMMENT "POSITION WAS APPARENTLY COMBINED WITH DR1 HIGH; SEVERAL AIRCRAFT TRANSMITTING ON ANOTHER FREQUENCY; POSITION WAS LATER DECOMBINED; CONTROLLER CHANGES; POSITION WORKED DEPARTURES OFF ANDREWS AFB, AND DAVISON ARMY AIRFIELD AS WELL AS NATIONAL; DUE TO PROXIMITY OF DULLES AND BALTIMORE, MOST DEPARTURES WERE TRANSFERRED TO ONE OF THESE FACILITIES RATHER THAN BEING CHANGED TO THE CENTER AS IN PREVIOUS FACILITIES"))


((FROM DR1-1)
(TO DAL209)
(TEXT   DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGHT ZERO)
(TIMES    63.04    66.01))


((FROM DAL209)
(TO DR1-1)
(TEXT   LEFT TO TWO EIGHTY DELTA TWO OH NINE)
(TIMES    66.65    69.08))

((FROM AAL1581)
(TO DR1-1)
(TEXT   APPROACH AMERICAN EIGHT AH FIFTEEN EIGHTY ONE IS WITH YOU OUT OF TWO)
(TIMES    93.55    96.11))

((FROM DR1-1)
(TO AAL1581)
(TEXT   AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTURE RADAR CONTACT CLIMB AND MAINTAIN ONE SEVEN THOUSAND)
(TIMES    96.63   101.06))

((FROM AAL1581)
(TO DR1-1)
(TEXT   UP TO ONE SEVEN THOUSAND AMERICAN FIFTEEN EIGHTY ONE)
(TIMES   101.30   103.46))

((FROM DR1-1)
(TO DAL209)
(TEXT   DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO)
(TIMES   106.51   109.48))

((FROM DAL209)
(TO DR1-1)
(TEXT   LEFT TO TWO FORTY DELTA TWO OH NINE)
(TIMES   109.85   112.06))

((FROM DR1-1)
(TO DAL209)
(TEXT   DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SEVEN ZERO DIRECT LINDEN WHEN ABLE AND RESUME YOUR OWN NAVIGATION)
(TIMES   195.95   201.46))

((FROM DAL209)
(TO DR1-1)
(TEXT   OKAY WE'LL GO DIRECT LINDEN RIGHT NOW DELTA TWO OH NINE)
(TIMES   201.98   204.77))

((FROM DR1-1)
(TO AAL1581)
(TEXT   AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING TWO NINER ZERO VECTORS FOR YOUR CLIMB)
(TIMES   205.16   208.22))

((FROM AAL1581)
(TO DR1-1)
(TEXT   TWO NINETY ON THE HEADING AMERICAN FIFTEEN EIGHTY ONE)
(TIMES   208.84   211.40))

((FROM DR1-1)
(TO DAL209)
(TEXT   DELTA TWO ZERO NINE CONTACT DULLES APPROACH CONTROL ONE THREE FOUR POINT TWO GOOD DAY)
(TIMES   215.76   219.70))

((FROM DAL209)
(TO DR1-1)
(TEXT   THIRTY FOUR TWO SO LONG)
(TIMES   220.26   221.74))

((FROM DR1-1)
(TO AAL1581)
(TEXT   AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING TWO THREE ZERO VECTOR AH FOR YOUR CLIMB)
(TIMES   265.03   269.83))

((FROM AAL1581)
(TO DR1-1)
(TEXT   TWO THIRTY ON THE HEADING AMERICAN FIFTEEN EIGHTY ONE)
(TIMES   270.72   273.24))

((FROM N99G)
(TO DR1-1)
(TEXT   HELLO WASHINGTON AERO STAR TWO SIX NINE NINE GOLF THREE THOUSAND)
(TIMES   299.63   302.55))

((FROM DR1-1)
(TO N99G)
(TEXT   AERO STAR NINE NINE GOLF FLY HEADING THREE THREE ZERO CLIMB AND MAINTAIN FOUR THOUSAND)
(TIMES   305.41   309.65))

((FROM N99G)
(TO DR1-1)
(TEXT   THREE THREE ZERO AND FOUR THOUSAND)
(TIMES   309.73   311.46))

((FROM DR1-1)
(TO DAL743)
(TEXT   DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE CONTROL CLIMB AND MAINTAIN FLIGHT LEVEL TWO THREE ZERO)
(TIMES   311.89

In [8]:
message_pattern = re.compile(
    r"\(\(FROM\s+(.*?)\)\s*"
    r"\(TO\s+(.*?)\)\s*"
    r"\(TEXT\s+(.*?)\)\s*"
    r"\(TIMES\s+([0-9.]+)\s+([0-9.]+)\)",
    re.DOTALL
)

matches = message_pattern.findall(raw_text)
len(matches)

397

In [9]:
rows = []
for frm, to, text, t1, t2 in matches:
    rows.append({
        "from": frm.strip(),
        "to": to.strip(),
        "text": text.strip(),
        "start_time": float(t1),
        "end_time": float(t2),
        "duration_s": float(t2) - float(t1)
    })

df_msgs = pd.DataFrame(rows)
df_msgs.head(20)

,from,to,text,start_time,end_time,duration_s
0,DR1-1,DAL209,DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...,63.04,66.01,2.97
1,DAL209,DR1-1,LEFT TO TWO EIGHTY DELTA TWO OH NINE,66.65,69.08,2.43
2,AAL1581,DR1-1,APPROACH AMERICAN EIGHT AH FIFTEEN EIGHTY ONE ...,93.55,96.11,2.56
3,DR1-1,AAL1581,AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...,96.63,101.06,4.43
4,AAL1581,DR1-1,UP TO ONE SEVEN THOUSAND AMERICAN FIFTEEN EIGH...,101.30,103.46,2.16
5,DR1-1,DAL209,DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO,106.51,109.48,2.97
6,DAL209,DR1-1,LEFT TO TWO FORTY DELTA TWO OH NINE,109.85,112.06,2.21
7,DR1-1,DAL209,DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...,195.95,201.46,5.51
8,DAL209,DR1-1,OKAY WE'LL GO DIRECT LINDEN RIGHT NOW DELTA TW...,201.98,204.77,2.79
9,DR1-1,AAL1581,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,205.16,208.22,3.06
10,AAL1581,DR1-1,TWO NINETY ON THE HEADING AMERICAN FIFTEEN EIG...,208.84,211.40,2.56
11,DR1-1,DAL209,DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...,215.76,219.70,3.94
12,DAL209,DR1-1,THIRTY FOUR TWO SO LONG,220.26,221.74,1.48
13,DR1-1,AAL1581,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,265.03,269.83,4.80
14,AAL1581,DR1-1,TWO THIRTY ON THE HEADING AMERICAN FIFTEEN EIG...,270.72,273.24,2.52
15,N99G,DR1-1,HELLO WASHINGTON AERO STAR TWO SIX NINE NINE G...,299.63,302.55,2.92
16,DR1-1,N99G,AERO STAR NINE NINE GOLF FLY HEADING THREE THR...,305.41,309.65,4.24
17,N99G,DR1-1,THREE THREE ZERO AND FOUR THOUSAND,309.73,311.46,1.73
18,DR1-1,DAL743,DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...,311.89,315.86,3.97
19,DR1-1,N99G,AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...,394.61,398.23,3.62

In [10]:
def clean_atc_text(text):
    text = text.upper()
    text = re.sub(r"\(UNINTELLIGIBLE.*?\)", " UNINTELLIGIBLE ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_msgs["clean_text"] = df_msgs["text"].apply(clean_atc_text)
df_msgs[["from", "to", "clean_text"]].head(20)

       from       to                                         clean_text
0     DR1-1   DAL209  DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...
1    DAL209    DR1-1               LEFT TO TWO EIGHTY DELTA TWO OH NINE
2   AAL1581    DR1-1  APPROACH AMERICAN EIGHT AH FIFTEEN EIGHTY ONE ...
3     DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...
4   AAL1581    DR1-1  UP TO ONE SEVEN THOUSAND AMERICAN FIFTEEN EIGH...
5     DR1-1   DAL209  DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO
6    DAL209    DR1-1                LEFT TO TWO FORTY DELTA TWO OH NINE
7     DR1-1   DAL209  DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...
8    DAL209    DR1-1  OKAY WE'LL GO DIRECT LINDEN RIGHT NOW DELTA TW...
9     DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...
10  AAL1581    DR1-1  TWO NINETY ON THE HEADING AMERICAN FIFTEEN EIG...
11    DR1-1   DAL209  DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...
12   DAL209    DR1-1                            THIRTY FOUR TWO SO LONG
13    DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...
14  AAL1581    DR1-1  TWO THIRTY ON THE HEADING AMERICAN FIFTEEN EIG...
15     N99G    DR1-1  HELLO WASHINGTON AERO STAR TWO SIX NINE NINE G...
16    DR1-1     N99G  AERO STAR NINE NINE GOLF FLY HEADING THREE THR...
17     N99G    DR1-1                 THREE THREE ZERO AND FOUR THOUSAND
18    DR1-1   DAL743  DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...
19    DR1-1     N99G  AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...

In [11]:
df_ctrl = df_msgs[df_msgs["from"].str.startswith("DR", na=False)].copy()
df_ctrl[["from", "to", "clean_text"]].head(20)

     from       to                                         clean_text
0   DR1-1   DAL209  DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...
3   DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...
5   DR1-1   DAL209  DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO
7   DR1-1   DAL209  DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...
9   DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...
11  DR1-1   DAL209  DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...
13  DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...
16  DR1-1     N99G  AERO STAR NINE NINE GOLF FLY HEADING THREE THR...
18  DR1-1   DAL743  DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...
19  DR1-1     N99G  AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...
21  DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN RIGHT HEADING...
23  DR1-1  AAL1581  AMERICAN FIFTEEN EIGHTY ONE CONTACT DULLES APP...
25  DR1-1   DAL743  DELTA SEVEN FORTY THREE PROCEED DIRECT LINDEN ...
26  DR1-1     N99G  AERO STAR NINE NINE GOLF TURN LEFT HEADING TWO...
29  DR1-1   USA237  U S AIR TWO THIRTY SEVEN WASHINGTON DEPARTURE ...
31  DR1-1   USA237                          MAINTAIN FIFTEEN THOUSAND
34  DR1-1   USA237  U S AIR TWO THIRTY SEVEN TURN LEFT HEADING TWO...
36  DR1-1  NWA1243  NORTHWEST TWELVE FORTY THREE WASHINGTON DEPART...
39  DR1-1  NWA1243           NORTHWEST TWELVE FORTY THREE AFFIRMATIVE
41  DR1-1   USA237  U S AIR TWO THIRTY SEVEN CLIMB AND MAINTAIN FL...

In [12]:
ENTITY_TYPES = [
    "CALLSIGN",
    "ACTION",
    "RUNWAY",
    "RUNWAY_HEADING",
    "HEADING",
    "ALTITUDE",
    "FLIGHT_LEVEL",
    "WAYPOINT",
    "FREQUENCY",
    "SPEED",
    "DIRECTION",
    "NAV_INSTRUCTION"
]

ENTITY_TYPES

['CALLSIGN',
 'ACTION',
 'RUNWAY',
 'RUNWAY_HEADING',
 'HEADING',
 'ALTITUDE',
 'FLIGHT_LEVEL',
 'WAYPOINT',
 'FREQUENCY',
 'SPEED',
 'DIRECTION',
 'NAV_INSTRUCTION']

In [13]:
patterns = {
    "HEADING": r"\bHEADING\s+((?:ZERO|ONE|TWO|THREE|FOUR|FIVE|SIX|SEVEN|EIGHT|NINER|NINE|OH|\s)+)\b",
    "ALTITUDE": r"\b(?:MAINTAIN|CLIMB AND MAINTAIN|DESCEND AND MAINTAIN)\s+((?:FLIGHT LEVEL\s+)?(?:ZERO|ONE|TWO|THREE|FOUR|FIVE|SIX|SEVEN|EIGHT|NINER|NINE|OH|\s)+)\b",
    "RUNWAY": r"\bRUNWAY\s+([0-9]{1,2}[LRC]?)\b",
    "WAYPOINT": r"\bDIRECT\s+([A-Z0-9]{3,10})\b",
    "FREQUENCY": r"\bONE\s+TWO[0-9A-Z\s]*POINT\s+[0-9A-Z\s]+\b|\b[0-9]{3}\.[0-9]{1,2}\b",
    "DIRECTION": r"\b(LEFT|RIGHT)\b"
}

action_keywords = [
    "TURN LEFT",
    "TURN RIGHT",
    "FLY HEADING",
    "CLIMB AND MAINTAIN",
    "DESCEND AND MAINTAIN",
    "MAINTAIN",
    "PROCEED DIRECT",
    "CONTACT",
    "RESUME YOUR OWN NAVIGATION",
    "JOIN",
    "EXPECT",
    "RADAR CONTACT",
    "DO NOT EXCEED",
    "EXPEDITE"
]

In [14]:
def weak_extract_entities(text):
    entities = {
        "ACTION": [],
        "HEADING": [],
        "ALTITUDE": [],
        "RUNWAY": [],
        "WAYPOINT": [],
        "FREQUENCY": [],
        "DIRECTION": []
    }

    for action in action_keywords:
        if action in text:
            entities["ACTION"].append(action)

    for label, pattern in patterns.items():
        matches = re.findall(pattern, text)
        if matches:
            entities[label] = matches if isinstance(matches, list) else [matches]

    return entities

df_ctrl["weak_entities"] = df_ctrl["clean_text"].apply(weak_extract_entities)
df_ctrl[["clean_text", "weak_entities"]].head(20)

,clean_text,weak_entities
0,DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...,"{'ACTION': ['TURN LEFT'], 'HEADING': ['TWO EIG..."
3,AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...,"{'ACTION': ['CLIMB AND MAINTAIN', 'MAINTAIN', ..."
5,DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO,"{'ACTION': ['TURN LEFT'], 'HEADING': ['TWO FOU..."
7,DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...,"{'ACTION': ['TURN RIGHT', 'RESUME YOUR OWN NAV..."
9,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,"{'ACTION': ['TURN LEFT'], 'HEADING': ['TWO NIN..."
11,DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...,"{'ACTION': ['CONTACT'], 'HEADING': [], 'ALTITU..."
13,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,"{'ACTION': ['TURN LEFT'], 'HEADING': ['TWO THR..."
16,AERO STAR NINE NINE GOLF FLY HEADING THREE THR...,"{'ACTION': ['FLY HEADING', 'CLIMB AND MAINTAIN..."
18,DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...,"{'ACTION': ['CLIMB AND MAINTAIN', 'MAINTAIN'],..."
19,AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...,"{'ACTION': ['CLIMB AND MAINTAIN', 'MAINTAIN'],..."
21,AMERICAN FIFTEEN EIGHTY ONE TURN RIGHT HEADING...,"{'ACTION': ['TURN RIGHT', 'RESUME YOUR OWN NAV..."
23,AMERICAN FIFTEEN EIGHTY ONE CONTACT DULLES APP...,"{'ACTION': ['CONTACT'], 'HEADING': [], 'ALTITU..."
25,DELTA SEVEN FORTY THREE PROCEED DIRECT LINDEN ...,"{'ACTION': ['PROCEED DIRECT', 'CONTACT', 'RESU..."
26,AERO STAR NINE NINE GOLF TURN LEFT HEADING TWO...,"{'ACTION': ['TURN LEFT', 'CONTACT', 'EXPECT'],..."
29,U S AIR TWO THIRTY SEVEN WASHINGTON DEPARTURE ...,"{'ACTION': ['CLIMB AND MAINTAIN', 'MAINTAIN', ..."
31,MAINTAIN FIFTEEN THOUSAND,"{'ACTION': ['MAINTAIN'], 'HEADING': [], 'ALTIT..."
34,U S AIR TWO THIRTY SEVEN TURN LEFT HEADING TWO...,"{'ACTION': ['TURN LEFT', 'RESUME YOUR OWN NAVI..."
36,NORTHWEST TWELVE FORTY THREE WASHINGTON DEPART...,"{'ACTION': ['CLIMB AND MAINTAIN', 'MAINTAIN', ..."
39,NORTHWEST TWELVE FORTY THREE AFFIRMATIVE,"{'ACTION': [], 'HEADING': [], 'ALTITUDE': [], ..."
41,U S AIR TWO THIRTY SEVEN CLIMB AND MAINTAIN FL...,"{'ACTION': ['CLIMB AND MAINTAIN', 'MAINTAIN'],..."

In [15]:
df_ctrl["actions"] = df_ctrl["weak_entities"].apply(lambda x: x["ACTION"])
df_ctrl["headings"] = df_ctrl["weak_entities"].apply(lambda x: x["HEADING"])
df_ctrl["altitudes"] = df_ctrl["weak_entities"].apply(lambda x: x["ALTITUDE"])
df_ctrl["runways"] = df_ctrl["weak_entities"].apply(lambda x: x["RUNWAY"])
df_ctrl["waypoints"] = df_ctrl["weak_entities"].apply(lambda x: x["WAYPOINT"])
df_ctrl["frequencies"] = df_ctrl["weak_entities"].apply(lambda x: x["FREQUENCY"])
df_ctrl["directions"] = df_ctrl["weak_entities"].apply(lambda x: x["DIRECTION"])

df_ctrl[[
    "clean_text",
    "actions",
    "headings",
    "altitudes",
    "runways",
    "waypoints",
    "frequencies",
    "directions"
]].head(30)

,clean_text,actions,headings,altitudes,runways,waypoints,frequencies,directions
0,DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...,[TURN LEFT],[TWO EIGHT ZERO],[],[],[],[],[LEFT]
3,AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...,"[CLIMB AND MAINTAIN, MAINTAIN, CONTACT, RADAR ...",[],[ONE SEVEN ],[],[],[],[]
5,DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO,[TURN LEFT],[TWO FOUR ZERO],[],[],[],[],[LEFT]
7,DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...,"[TURN RIGHT, RESUME YOUR OWN NAVIGATION]",[TWO SEVEN ZERO ],[],[],[LINDEN],[],[RIGHT]
9,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,[TURN LEFT],[TWO NINER ZERO ],[],[],[],[],[LEFT]
11,DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...,[CONTACT],[],[],[],[],[],[]
13,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,[TURN LEFT],[TWO THREE ZERO ],[],[],[],[],[LEFT]
16,AERO STAR NINE NINE GOLF FLY HEADING THREE THR...,"[FLY HEADING, CLIMB AND MAINTAIN, MAINTAIN]",[THREE THREE ZERO ],[FOUR ],[],[],[],[]
18,DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[FLIGHT LEVEL TWO THREE ZERO],[],[],[],[]
19,AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[],[],[],[],[]
21,AMERICAN FIFTEEN EIGHTY ONE TURN RIGHT HEADING...,"[TURN RIGHT, RESUME YOUR OWN NAVIGATION, JOIN]",[THREE TWO ZERO ],[],[],[],[],[RIGHT]
23,AMERICAN FIFTEEN EIGHTY ONE CONTACT DULLES APP...,[CONTACT],[],[],[],[],[],[]
25,DELTA SEVEN FORTY THREE PROCEED DIRECT LINDEN ...,"[PROCEED DIRECT, CONTACT, RESUME YOUR OWN NAVI...",[],[],[],[LINDEN],[ONE TWO ZERO POINT SIX FIVE],[]
26,AERO STAR NINE NINE GOLF TURN LEFT HEADING TWO...,"[TURN LEFT, CONTACT, EXPECT]",[TWO SEVEN ZERO ],[],[],[],[ONE TWO SIX POINT SIX FIVE EXPECT VECTORS CAS...,[LEFT]
29,U S AIR TWO THIRTY SEVEN WASHINGTON DEPARTURE ...,"[CLIMB AND MAINTAIN, MAINTAIN, CONTACT, RADAR ...",[],[ONE FIVE ],[],[],[],[]
31,MAINTAIN FIFTEEN THOUSAND,[MAINTAIN],[],[],[],[],[],[]
34,U S AIR TWO THIRTY SEVEN TURN LEFT HEADING TWO...,"[TURN LEFT, RESUME YOUR OWN NAVIGATION, JOIN]",[TWO ONE ZERO ],[],[],[],[],[LEFT]
36,NORTHWEST TWELVE FORTY THREE WASHINGTON DEPART...,"[CLIMB AND MAINTAIN, MAINTAIN, CONTACT, RADAR ...",[],[ONE SEVEN ],[],[],[],[]
39,NORTHWEST TWELVE FORTY THREE AFFIRMATIVE,[],[],[],[],[],[],[]
41,U S AIR TWO THIRTY SEVEN CLIMB AND MAINTAIN FL...,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[FLIGHT LEVEL TWO ONE ZERO],[],[],[],[]
43,LET ME KNOW IF YOU GET ON TOP U S AIR TWO THIR...,[],[],[],[],[],[],[]
44,U S AIR TWO THIRTY SEVEN IF YOU GET ON TOP ADV...,[],[],[],[],[],[],[]
46,NORTHWEST TWELVE FORTY THREE TURN LEFT HEADING...,"[TURN LEFT, EXPECT]",[TWO NINER ZERO ],[],[],[],[],[LEFT]
48,NORTHWEST TWELVE FORTY THREE CONTACT AH DULLES...,[CONTACT],[],[],[],[],[],[]
50,SABRE ONE SIX ZERO WHISKEY WASHINGTON,[],[],[],[],[],[],[]
51,CLIMB AND MAINTAIN FLIGHT LEVEL TWO THREE ZERO,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[FLIGHT LEVEL TWO THREE ZERO],[],[],[],[]
53,SABRE LINER SIX ZERO WHISKEY FLY HEADING TWO T...,"[FLY HEADING, RESUME YOUR OWN NAVIGATION, JOIN]",[TWO TWO ZERO ],[],[],[],[],[]
54,U S AIR TWO THIRTY SEVEN MAINTAIN FLIGHT LEVEL...,"[MAINTAIN, CONTACT]",[],[FLIGHT LEVEL TWO ONE ZERO ],[],[],[],[]
56,DELTA SIX TWENTY ONE DID YOU CALL,[],[],[],[],[],[],[]
57,DELTA SIX TWENTY ONE REDUCE TO TWO HUNDRED AND...,[FLY HEADING],[TWO ZERO ZERO],[],[],[],[],[]

In [16]:
df_ctrl["callsign"] = df_ctrl["to"].str.strip().str.upper()
df_ctrl[["callsign", "clean_text"]].head(20)

   callsign                                         clean_text
0    DAL209  DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...
3   AAL1581  AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...
5    DAL209  DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO
7    DAL209  DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...
9   AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...
11   DAL209  DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...
13  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...
16     N99G  AERO STAR NINE NINE GOLF FLY HEADING THREE THR...
18   DAL743  DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...
19     N99G  AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...
21  AAL1581  AMERICAN FIFTEEN EIGHTY ONE TURN RIGHT HEADING...
23  AAL1581  AMERICAN FIFTEEN EIGHTY ONE CONTACT DULLES APP...
25   DAL743  DELTA SEVEN FORTY THREE PROCEED DIRECT LINDEN ...
26     N99G  AERO STAR NINE NINE GOLF TURN LEFT HEADING TWO...
29   USA237  U S AIR TWO THIRTY SEVEN WASHINGTON DEPARTURE ...
31   USA237                          MAINTAIN FIFTEEN THOUSAND
34   USA237  U S AIR TWO THIRTY SEVEN TURN LEFT HEADING TWO...
36  NWA1243  NORTHWEST TWELVE FORTY THREE WASHINGTON DEPART...
39  NWA1243           NORTHWEST TWELVE FORTY THREE AFFIRMATIVE
41   USA237  U S AIR TWO THIRTY SEVEN CLIMB AND MAINTAIN FL...

In [17]:
training_df = df_ctrl[[
    "callsign",
    "clean_text",
    "actions",
    "headings",
    "altitudes",
    "runways",
    "waypoints",
    "frequencies",
    "directions"
]].copy()

training_df.head(30)

,callsign,clean_text,actions,headings,altitudes,runways,waypoints,frequencies,directions
0,DAL209,DELTA TWO ZERO NINE TURN LEFT HEADING TWO EIGH...,[TURN LEFT],[TWO EIGHT ZERO],[],[],[],[],[LEFT]
3,AAL1581,AMERICAN FIFTEEN EIGHTY ONE WASHINGTON DEPARTU...,"[CLIMB AND MAINTAIN, MAINTAIN, CONTACT, RADAR ...",[],[ONE SEVEN ],[],[],[],[]
5,DAL209,DELTA TWO OH NINE TURN LEFT HEADING TWO FOUR ZERO,[TURN LEFT],[TWO FOUR ZERO],[],[],[],[],[LEFT]
7,DAL209,DELTA TWO OH NINE TURN RIGHT AH HEADING TWO SE...,"[TURN RIGHT, RESUME YOUR OWN NAVIGATION]",[TWO SEVEN ZERO ],[],[],[LINDEN],[],[RIGHT]
9,AAL1581,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,[TURN LEFT],[TWO NINER ZERO ],[],[],[],[],[LEFT]
11,DAL209,DELTA TWO ZERO NINE CONTACT DULLES APPROACH CO...,[CONTACT],[],[],[],[],[],[]
13,AAL1581,AMERICAN FIFTEEN EIGHTY ONE TURN LEFT HEADING ...,[TURN LEFT],[TWO THREE ZERO ],[],[],[],[],[LEFT]
16,N99G,AERO STAR NINE NINE GOLF FLY HEADING THREE THR...,"[FLY HEADING, CLIMB AND MAINTAIN, MAINTAIN]",[THREE THREE ZERO ],[FOUR ],[],[],[],[]
18,DAL743,DELTA SEVEN FORTY THREE WASHINGTON DEPARTURE C...,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[FLIGHT LEVEL TWO THREE ZERO],[],[],[],[]
19,N99G,AERO STAR NINE NINE GOLF CLIMB AND MAINTAIN AH...,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[],[],[],[],[]
21,AAL1581,AMERICAN FIFTEEN EIGHTY ONE TURN RIGHT HEADING...,"[TURN RIGHT, RESUME YOUR OWN NAVIGATION, JOIN]",[THREE TWO ZERO ],[],[],[],[],[RIGHT]
23,AAL1581,AMERICAN FIFTEEN EIGHTY ONE CONTACT DULLES APP...,[CONTACT],[],[],[],[],[],[]
25,DAL743,DELTA SEVEN FORTY THREE PROCEED DIRECT LINDEN ...,"[PROCEED DIRECT, CONTACT, RESUME YOUR OWN NAVI...",[],[],[],[LINDEN],[ONE TWO ZERO POINT SIX FIVE],[]
26,N99G,AERO STAR NINE NINE GOLF TURN LEFT HEADING TWO...,"[TURN LEFT, CONTACT, EXPECT]",[TWO SEVEN ZERO ],[],[],[],[ONE TWO SIX POINT SIX FIVE EXPECT VECTORS CAS...,[LEFT]
29,USA237,U S AIR TWO THIRTY SEVEN WASHINGTON DEPARTURE ...,"[CLIMB AND MAINTAIN, MAINTAIN, CONTACT, RADAR ...",[],[ONE FIVE ],[],[],[],[]
31,USA237,MAINTAIN FIFTEEN THOUSAND,[MAINTAIN],[],[],[],[],[],[]
34,USA237,U S AIR TWO THIRTY SEVEN TURN LEFT HEADING TWO...,"[TURN LEFT, RESUME YOUR OWN NAVIGATION, JOIN]",[TWO ONE ZERO ],[],[],[],[],[LEFT]
36,NWA1243,NORTHWEST TWELVE FORTY THREE WASHINGTON DEPART...,"[CLIMB AND MAINTAIN, MAINTAIN, CONTACT, RADAR ...",[],[ONE SEVEN ],[],[],[],[]
39,NWA1243,NORTHWEST TWELVE FORTY THREE AFFIRMATIVE,[],[],[],[],[],[],[]
41,USA237,U S AIR TWO THIRTY SEVEN CLIMB AND MAINTAIN FL...,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[FLIGHT LEVEL TWO ONE ZERO],[],[],[],[]
43,USA237,LET ME KNOW IF YOU GET ON TOP U S AIR TWO THIR...,[],[],[],[],[],[],[]
44,USA237,U S AIR TWO THIRTY SEVEN IF YOU GET ON TOP ADV...,[],[],[],[],[],[],[]
46,NWA1243,NORTHWEST TWELVE FORTY THREE TURN LEFT HEADING...,"[TURN LEFT, EXPECT]",[TWO NINER ZERO ],[],[],[],[],[LEFT]
48,NWA1243,NORTHWEST TWELVE FORTY THREE CONTACT AH DULLES...,[CONTACT],[],[],[],[],[],[]
50,N60W,SABRE ONE SIX ZERO WHISKEY WASHINGTON,[],[],[],[],[],[],[]
51,N60W,CLIMB AND MAINTAIN FLIGHT LEVEL TWO THREE ZERO,"[CLIMB AND MAINTAIN, MAINTAIN]",[],[FLIGHT LEVEL TWO THREE ZERO],[],[],[],[]
53,N60W,SABRE LINER SIX ZERO WHISKEY FLY HEADING TWO T...,"[FLY HEADING, RESUME YOUR OWN NAVIGATION, JOIN]",[TWO TWO ZERO ],[],[],[],[],[]
54,USA237,U S AIR TWO THIRTY SEVEN MAINTAIN FLIGHT LEVEL...,"[MAINTAIN, CONTACT]",[],[FLIGHT LEVEL TWO ONE ZERO ],[],[],[],[]
56,DAL621,DELTA SIX TWENTY ONE DID YOU CALL,[],[],[],[],[],[],[]
57,DAL621,DELTA SIX TWENTY ONE REDUCE TO TWO HUNDRED AND...,[FLY HEADING],[TWO ZERO ZERO],[],[],[],[],[]